apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mod-reading-room
  namespace: folio-test
spec:
  destination:
    namespace: folio-test
    server: https://kubernetes.default.svc
  project: folio-test
  sources:
  - chart: mod-reading-room
    helm:
      valueFiles:
      - $values/folio-test/modules/mod-reading-room/overrides.yaml
      - $values/folio-test/common/resources.yaml
      - $values/folio-test/common/sidecar.yaml
      - $values/folio-test/common/probes.yaml
      - $values/folio-test/modules/mod-reading-room/replicas.yaml
      - $values/folio-test/common/java_opts.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2
    targetRevision: 1.0.49
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: main
