apiVersion: apps/v1
kind: Deployment
metadata:
  name: folio-custom-theme
spec:
  selector:
    matchLabels:
      app: folio-custom-theme
  template:
    metadata:
      labels:
        app: folio-custom-theme
    spec:
      containers:
        - name: folio-custom-theme
          image: ghcr.io/sul-dlss/folio-custom-theme:main
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: ghcr
---
apiVersion: v1
kind: Service
metadata:
  name: folio-custom-theme
spec:
  selector:
    app: folio-custom-theme
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
