apiVersion: batch/v1
kind: CronJob
metadata:
  name: srs-modules-restart
  namespace: folio-prod
spec:
  concurrencyPolicy: Forbid
  timeZone: "America/Los_Angeles"
  schedule: "30 5 * * 1-5"
  # schedule: '0 0 29 2 1' # noop
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 604800  # 7 days in seconds; missed jobs won't be picked up if unsuspended after a week
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      ttlSecondsAfterFinished: 14400 # 4 hours
      template:
        spec:
          serviceAccountName: folio-k8s
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnamilegacy/kubectl
              env:
                - name: SRS_MODULES
                  value: | 
                    mod-data-import 
                    mod-di-converter-storage 
                    mod-inventory 
                    mod-inventory-storage 
                    mod-source-record-storage 
                    mod-source-record-manager 
                    mod-copycat
              command: [ "/bin/bash", "-c", "--" ]
              args: [ "for M in $SRS_MODULES; do kubectl -n $namespace rollout restart deployments/$M; done" ]
