apiVersion: v1
kind: Service
metadata:
  name: mod-erm-usage-harvester-hazelcast
  namespace: folio-test
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: mod-erm-usage-harvester
    app.kubernetes.io/instance: mod-erm-usage-harvester
  ports:
    - name: hazelcast
      protocol: TCP
      port: 5701
      targetPort: 5701
