ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: "folio-ncip-dev.stanford.edu"
      paths:
        - path: '/'
          pathType: Prefix
          servicePort: 80
