apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-db-credentials
  namespace: $namespace
spec:
  type: kv-v2
  mount: puppet
  # path of the secret
  path: application/folio-k8s/$namespace/db-credentials
  # dest k8s secret
  destination:
    name: db-credentials
    create: true
    overwrite: true
  # static secret refresh interval
  refreshAfter: 10m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-eureka-common
  namespace: $namespace
spec:
  type: kv-v2
  mount: puppet
  # path of the secret
  path: application/folio-k8s/$namespace/eureka-common
  # dest k8s secret
  destination:
    name: eureka-common
    create: true
    overwrite: true
  # static secret refresh interval
  refreshAfter: 10m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-eureka-edge
  namespace: $namespace
spec:
  type: kv-v2
  mount: puppet
  # path of the secret
  path: application/folio-k8s/$namespace/eureka-edge
  # dest k8s secret
  destination:
    name: eureka-edge
    create: true
    overwrite: true
  # static secret refresh interval
  refreshAfter: 10m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-kafka-credentials
  namespace: $namespace
spec:
  type: kv-v2
  mount: puppet
  # path of the secret
  path: application/folio-k8s/$namespace/kafka-credentials
  # dest k8s secret
  destination:
    name: kafka-credentials
    create: true
    overwrite: true
  # static secret refresh interval
  refreshAfter: 10m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-keycloak-credentials
  namespace: $namespace
spec:
  type: kv-v2
  mount: puppet
  # path of the secret
  path: application/folio-k8s/$namespace/keycloak-credentials
  # dest k8s secret
  destination:
    name: keycloak-credentials
    create: true
    overwrite: true
  # static secret refresh interval
  refreshAfter: 10m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-kong-credentials
  namespace: $namespace
spec:
  type: kv-v2
  mount: puppet
  # path of the secret
  path: application/folio-k8s/$namespace/kong-credentials
  # dest k8s secret
  destination:
    name: kong-credentials
    create: true
    overwrite: true
  # static secret refresh interval
  refreshAfter: 10m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-opensearch-credentials
  namespace: $namespace
spec:
  type: kv-v2
  mount: puppet
  # path of the secret
  path: application/folio-k8s/$namespace/opensearch-credentials
  # dest k8s secret
  destination:
    name: opensearch-credentials
    create: true
    overwrite: true
  # static secret refresh interval
  refreshAfter: 10m
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-s3-credentials
  namespace: $namespace
spec:
  type: kv-v2
  mount: puppet
  # path of the secret
  path: application/folio-k8s/$namespace/s3-credentials
  # dest k8s secret
  destination:
    name: s3-credentials
    create: true
    overwrite: true
  # static secret refresh interval
  refreshAfter: 10m