apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mod-finance-storage
  namespace: folio-prod
spec:
  destination:
    namespace: folio-prod
    server: https://kubernetes.default.svc
  project: folio-prod
  sources:
  - chart: mod-finance-storage
    helm:
      valueFiles:
      - $values/folio-prod/modules/mod-finance-storage/overrides.yaml
      - $values/folio-prod/modules/mod-finance-storage/resources.yaml
      - $values/folio-prod/common/sidecar.yaml
      - $values/folio-prod/common/probes.yaml
      - $values/folio-prod/modules/mod-finance-storage/replicas.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2
    targetRevision: 8.5.48
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: main
