apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: folio-dev
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - vault-static-secret.yaml
images:
  - name: scriptshifter
    newName: ghcr.io/sul-dlss/scriptshifter
    newTag: 2.22.0
