apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-scriptshifter-secret
  namespace: folio-dev
spec:
  type: kv-v2
  mount: puppet
  # path of the secret
  path: application/folio-k8s/folio-dev/scriptshifter
  # dest k8s secret
  destination:
    name: scriptshifter-secret
    create: true
    overwrite: true
  # static secret refresh interval
  refreshAfter: 10m