apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mail
  namespace: folio-stage
operation:
  sync:
    syncStrategy:
      hook: {}
spec:
  destination:
    namespace: folio-stage
    server: https://kubernetes.default.svc
  sources:
    - chart: mail
      repoURL: https://bokysan.github.io/docker-postfix
      targetRevision: 5.1.0
      helm:
        valueFiles:
          - $values/folio-stage/infrastructure/postfix.yaml
    - repoURL: https://github.com/sul-dlss/folio-eureka
      targetRevision: main
      ref: values
  project: folio-stage
