apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: setae-api
  namespace: folio-stage
  labels:
    application: infrastructure
spec:
  project: folio-stage
  destination:
    server: https://kubernetes.default.svc
    namespace: folio-stage
  source:
    path: folio-stage/infrastructure
    directory:
      include: 'setae.yaml'
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: main