apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    application: app-platform-complete-2.5.10
    type: module
  name: mod-remote-storage
  namespace: folio-dev
spec:
  destination:
    namespace: folio-dev
    server: https://kubernetes.default.svc
  project: folio-dev
  sources:
  - chart: mod-remote-storage
    helm:
      valueFiles:
      - $values/folio-dev/modules/mod-remote-storage/overrides.yaml
      - $values/folio-dev/common/resources.yaml
      - $values/folio-dev/common/sidecar.yaml
      - $values/folio-dev/common/probes.yaml
      - $values/folio-dev/common/java_opts.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2
    targetRevision: 3.0.55
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: main
