apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: setae-api
  namespace: folio-test
  labels:
    application: infrastructure
spec:
  project: folio-test
  destination:
    server: https://kubernetes.default.svc
    namespace: folio-test
  source:
    path: folio-test/infrastructure
    directory:
      include: 'setae.yaml'
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: main