apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    application: module
  name: mod-ebsconet
  namespace: folio-dev
spec:
  destination:
    namespace: folio-dev
    server: https://kubernetes.default.svc
  project: folio-dev
  sources:
  - chart: mod-ebsconet
    helm:
      valueFiles:
      - $values/folio-dev/modules/mod-ebsconet/overrides.yaml
      - $values/folio-dev/common/resources.yaml
      - $values/folio-dev/common/sidecar.yaml
      - $values/folio-dev/common/probes.yaml
      - $values/folio-dev/common/java_opts.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2
    targetRevision: 2.1.54
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: main
