apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: folio-listenerset
  namespace: folio-prod
  labels:
    type: infrastructure
spec:
  project: folio-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: folio-prod
  source:
    path: folio-prod/listenerset
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: main
