apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - policies.yaml

# Inject the exact same IP list into both resources automatically
patches:
  - path: ip_list.yaml
    target:
      kind: SecurityPolicy
      name: folio-ip-and-cors-policy
  - path: ip_list.yaml
    target:
      kind: SecurityPolicy
      name: folio-ip-only-policy