apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: folio-dev

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/0/value
        value: folio-dev
    target:
      kind: CronJob
      name: db-modules-restart
  - patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/0/value
        value: folio-dev
    target:
      kind: CronJob
      name: srs-modules-restart
  - patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/0/value
        value: folio-dev
    target:
      kind: CronJob
      name: kafka-modules-restart