apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mod-marc-migrations
  namespace: folio-dev
spec:
  destination:
    namespace: folio-dev
    server: https://kubernetes.default.svc
  project: folio-dev
  sources:
  - chart: mod-marc-migrations
    helm:
      valueFiles:
      - $values/folio-dev/modules/mod-marc-migrations/overrides.yaml
      - $values/folio-dev/common/resources.yaml
      - $values/folio-dev/common/sidecar.yaml
      - $values/folio-dev/common/probes.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2
    targetRevision: 1.0.49
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: main
