apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    application: app-edge-complete-2.0.16
    type: edge
  name: edge-ncip
  namespace: folio-test
spec:
  destination:
    namespace: folio-test
    server: https://kubernetes.default.svc
  project: folio-test
  sources:
  - chart: edge-ncip
    helm:
      valueFiles:
      - $values/folio-test/modules/edge-ncip/overrides.yaml
      - $values/folio-test/modules/edge-ncip/resources.yaml
      - $values/folio-test/common/probes.yaml
      - $values/folio-test/modules/edge-ncip/service.yaml
      - $values/folio-test/modules/edge-ncip/java_opts.yaml
      - $values/folio-test/modules/edge-ncip/extra_env.yaml
    repoURL: https://sul-dlss.github.io/folio-helm-v2
    targetRevision: 1.10.1
  - ref: values
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: main
