extraDeploy:
  - |
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: edge-ncip-backend
      namespace: folio-test
      labels:
        access: protected-standard
    spec:
      rules:
      - backendRefs:
        - name: edge-ncip
          port: 80
        matches:
          - path:
              type: PathPrefix
              value: /
      hostnames:
      - folio-ncip-test.stanford.edu
      parentRefs:
      - name: default
        namespace: envoy-gateway-system
