apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: folio-ip-and-cors-policy
  namespace: folio-prod
spec:
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      matchLabels:
        access: cors-ip-allowlist
  cors:
    allowOrigins:
      - http://kong:8000
    allowMethods:
      - GET
      - OPTIONS
      - POST
      - PUT
  authorization: {}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: folio-ip-only-policy
  namespace: folio-prod
spec:
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      matchLabels:
        access: ip-allowlist
  authorization: {}
