apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: setae-api
  namespace: folio-prod
  labels:
    type: infrastructure
spec:
  project: folio-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: folio-prod
  source:
    path: folio-prod/infrastructure
    directory:
      include: 'setae.yaml'
    repoURL: https://github.com/sul-dlss/folio-eureka
    targetRevision: main