image:
  pullPolicy: Always
  repository: ghcr.io/sul-dlss/folio-platform-complete
  tag: R1-2025-csp-4-eureka-prod
replicaCount: 2

startupProbeEnabled : true
livenessProbeEnabled : true
readinessProbeEnabled : true

extraDeploy:
  - |
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: platform-complete-backend
      namespace: folio-prod
    spec:
      rules:
      - backendRefs:
        - name: platform-complete
          port: 80
        matches:
          - path:
              type: PathPrefix
              value: /
      hostnames:
      - folio.stanford.edu
      parentRefs:
      - name: default
        namespace: envoy-gateway-system
    ---
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: SecurityPolicy
    metadata:
      name: platform-complete-ip-limits
      namespace: folio-prod
    spec:
        targetRefs:
          - kind: HTTPRoute
            group: gateway.networking.k8s.io
            name: platform-complete-backend
        authorization:
          defaultAction: Deny
          rules:
            - action: Allow
              principal:
                clientCIDRs:
                - "52.9.21.118/32"
                - "54.153.8.197/32"
                - "52.53.107.5/32"
                - "18.144.135.31/32"
                - "23.244.192.27/32"
                - "54.245.203.243/32"
                - "171.64.0.0/14"
                - "10.32.0.0/15"
                - "10.34.0.0/15"
                - "10.96.0.0/11"
                - "10.98.0.0/15"
                - "10.130.0.0/18"
                - "10.130.64.0/18"
                - "10.130.128.0/18"
                - "10.130.192.0/18"
                - "172.24.0.0/14"
                - "172.20.206.128/25"
                - "172.20.207.0/25"
                - "171.66.16.0/21"
                - "171.66.24.0/21"
                - "171.66.176.0/20"
                - "204.63.231.0/25"
                - "10.109.48.0/25"
                - "10.109.48.128/25"
                - "171.66.1.0/24"
                - "35.203.130.101/32"
                - "35.203.131.135/32"
                - "35.192.213.120/32"
                - "104.198.197.19/32"
                - "216.54.57.225/32"
                - "20.230.202.69/32"
                - "52.175.234.32/32"
                - "20.29.204.55/32"
                - "52.250.48.144/32"
                - "10.142.204.81/32"
                - "10.142.204.82/32"
                - "62.153.143.224/28"
                - "87.129.225.56/29"
    ---
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: SecurityPolicy
    metadata:
      name: platform-complete-cors
      namespace: folio-prod
    spec:
        targetRefs:
          - kind: HTTPRoute
            group: gateway.networking.k8s.io
            name: platform-complete-backend
        cors:
          allowOrigins:
          - http://kong:8000
          allowMethods:
          - GET
          - OPTIONS
          - POST
          - PUT
