apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-modules-restart
spec: 
  concurrencyPolicy: Forbid
  timeZone: "America/Los_Angeles"
  schedule: "59 23 * * *"
  startingDeadlineSeconds: 86400
  suspend: true
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 7200
      ttlSecondsAfterFinished: 14400
      template:
        spec:
          serviceAccountName: folio-k8s
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnamilegacy/kubectl 
              env:
                - name: NAMESPACE
                  value: PLACEHOLDER
                - name: DB_MODULES
                  value: |- 
                    mod-agreements
                    mod-audit
                    mod-batch-print
                    mod-calendar
                    mod-bulk-operations
                    mod-circulation-storage
                    mod-configuration
                    mod-copycat
                    mod-courses
                    mod-data-export
                    mod-data-export-spring
                    mod-data-export-worker
                    mod-data-import
                    mod-di-converter-storage
                    mod-email
                    mod-erm-usage
                    mod-erm-usage-harvester
                    mod-eusage-reports
                    mod-event-config
                    mod-feesfines
                    mod-finance-storage
                    mod-fqm-manager
                    mod-inventory-storage
                    mod-invoice-storage
                    mod-licenses
                    mod-lists
                    mod-login-keycloak
                    mod-notes 
                    mod-notify
                    mod-okapi-facade
                    mod-orders-storage
                    mod-organizations-storage
                    mod-password-validator
                    mod-patron-blocks
                    mod-permissions
                    mod-pubsub
                    mod-quick-marc
                    mod-roles-keycloak
                    mod-search
                    mod-serials-management
                    mod-settings
                    mod-source-record-manager
                    mod-source-record-storage
                    mod-tags
                    mod-template-engine
                    mod-users
                    mod-users-keycloak
              command: [ "/bin/bash", "-c", "--" ]
              args: [ "for M in $DB_MODULES; do kubectl -n $NAMESPACE rollout restart deployment/$M; sleep 60; done" ]