service:
  type: NodePort
  ports:
    - name: sru
      protocol: TCP
      port: 80
      containerPort: 9997
      targetPort: sru
    - name: z3950
      protocol: TCP
      port: 210
      containerPort: 9997
      targetPort: z3950
    - name: zserver
      protocol: TCP
      port: 9997
      containerPort: 9997
      targetPort: zserver

extraDeploy:
  - |
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: BackendTrafficPolicy
    metadata:
      name: sru-custom-error-page
      namespace: folio-stage
    spec:
        targetRefs:
          - kind: HTTPRoute
            group: gateway.networking.k8s.io
            name: sru-backend
        responseOverride:
          - match:
              statusCodes:
              - type: Value
                value: 403
            response:
              contentType: text/html
              body:
                type: Inline
                inline: "You are not authorized to access FOLIO. A connection to the Stanford Network is required."
    ---
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: sru-backend
      namespace: folio-stage
    spec:
      rules:
      - backendRefs:
        - name: mod-z3950
          port: 80
        matches:
          - path:
              type: PathPrefix
              value: /
      hostnames:
      - folio-sru-stage.stanford.edu
      parentRefs:
      - name: default
        namespace: envoy-gateway-system
    ---
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: SecurityPolicy
    metadata:
      name: sru-ip-limits
      namespace: folio-stage
    spec:
        targetRefs:
          - kind: HTTPRoute
            group: gateway.networking.k8s.io
            name: sru-backend
        authorization:
          defaultAction: Deny
          rules:
            - action: Allow
              principal:
                clientCIDRs:
                - "52.53.107.5/32"
                - "18.144.135.31/32"
                - "23.244.192.27/32"
                - "54.245.203.243/32"
                - "34.214.229.235/32"
                - "35.161.222.214/32"
                - "18.219.235.193/32"
                - "171.64.0.0/14"
                - "10.32.0.0/15"
                - "10.34.0.0/15"
                - "10.96.0.0/11"
                - "10.98.0.0/15"
                - "10.130.0.0/18"
                - "10.130.64.0/18"
                - "10.130.128.0/18"
                - "10.130.192.0/18"
                - "172.24.0.0/14"
                - "172.20.206.128/25"
                - "172.20.207.0/25"
                - "171.66.16.0/21"
                - "171.66.24.0/21"
                - "171.66.176.0/20"
                - "204.63.231.0/25"
                - "10.109.48.0/25"
                - "10.109.48.128/25"
                - "171.66.1.0/24"
                - "35.203.130.101/32"
                - "35.203.131.135/32"
                - "35.192.213.120/32"
                - "104.198.197.19/32"
                - "52.175.234.32/32"
                - "20.29.204.55/32"
                - "52.250.48.144/32"
                - "10.142.204.81/32"
                - "10.142.204.82/32"
                - "62.153.143.224/28"
                - "87.129.225.56/29"
                - "52.38.29.98/32"

    ---
    apiVersion: gateway.envoyproxy.io/v1alpha1
    kind: SecurityPolicy
    metadata:
      name: sru-cors
      namespace: folio-stage
    spec:
        targetRefs:
          - kind: HTTPRoute
            group: gateway.networking.k8s.io
            name: sru-backend
        cors:
          allowOrigins:
          - http://kong:8000
          allowMethods:
          - GET
          - OPTIONS
          - POST
          - PUT
