apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mgr-apps
  namespace: folio-dev
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - mgr_app: mgr-applications
        version: 0.0.16
      - mgr_app: mgr-tenants
        version: 0.0.16
      - mgr_app: mgr-tenant-entitlements
        version: 0.0.16
  template:
    metadata:
      name: "{{mgr_app}}"
      namespace: folio-dev
    spec:
      project: folio-dev
      syncPolicy:
        automated:
          enabled: true
        syncOptions:
          - CreateNamespace=true
      sources:
      - repoURL: https://sul-dlss.github.io/folio-helm-v2/
        targetRevision: "{{version}}"
        chart: "{{mgr_app}}"
        helm:
          valueFiles:
            - $values/folio-dev/{{mgr_app}}.yaml
      - ref: values
        repoURL: https://github.com/sul-dlss/folio-eureka/
        targetRevision: argo-cd
      destination:
        namespace: folio-dev
        server: https://kubernetes.default.svc
